### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by ghost** [rovo89/GenyFlash#5]
Will there be a shell script version? I tried installing using Wine but then realized it cant recognise ADB commands

**Comment by rovo89** [comment]
I have no plans for this, as I wouldn't be able to test it anyway. But the install/uninstall scripts are very small and mostly consist of adb commands. It should be easy for someone with a little Linux knowledge to port it to Linux. Actually, it seems that @maxiwell has already done this, but forgot to send a pull request... ;)

**Comment by ghost** [comment]
maxiwell's script works fine. But i got the same installed but not enabled error as mentioned by users on XDA. Using Genymotion 2.5 on Ubuntu 14.04
Accidentally deleted the virtual device. Will post the log (if I can get any) after setting it up again

**Comment by rovo89** [comment]
Ok, it would be good if you can reproduce the issue. If you can, please let me know which image / device you have set up, so I can try it myself.

**Comment by ghost** [comment]
I used Nexus 4 5.0

**Comment by ghost** [comment]
![screen](https://cloud.githubusercontent.com/assets/8400485/8411008/36f2e1e6-1e9f-11e5-92b6-8b32971ad4cb.png)

![screen1](https://cloud.githubusercontent.com/assets/8400485/8411014/3e3476c2-1e9f-11e5-881f-7e7ad938251a.png)

06-29 11:01:09.178 I/Xposed  (  460): -----------------
06-29 11:01:09.178 I/Xposed  (  460): Starting Xposed version 65, compiled for SDK 21
06-29 11:01:09.178 I/Xposed  (  460): Device: Google Nexus 4 - Lollipop (Genymotion), Android version 5.0 (SDK 21)
06-29 11:01:09.178 I/Xposed  (  460): ROM: vbox86p-userdebug 5.0 LRX21M eng.buildbot.20150610.004120 test-keys
06-29 11:01:09.178 I/Xposed  (  460): Build fingerprint: generic/vbox86p/vbox86p:5.0/LRX21M/buildbot06100044:userdebug/test-keys
06-29 11:01:09.178 I/Xposed  (  460): Platform: x86, 32-bit binary, system server: yes
06-29 11:01:09.178 I/Xposed  (  460): SELinux enabled: no, enforcing: no
06-29 11:01:11.489 I/Xposed  (  460): -----------------
06-29 11:01:11.505 I/Xposed  (  460): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
06-29 11:01:12.436 I/Xposed  (  460): Detected ART runtime
06-29 11:01:12.682 I/Xposed  (  460): Found Xposed class de/robv/android/xposed/XposedBridge, now initializing

Thoughts @rovo89 ?

**Comment by ghost** [comment]
Just installed alpha 4 and everything works fine now. Thanks @rovo89

**Comment by rovo89** [comment]
Great! Back to the original topic then. The scripts by @maxiwell work fine? Then I can cherry-pick them...

**Comment by ghost** [comment]
Yes, no issues with his scripts. Tried both install and uninstall. Worked fine

**Comment by rovo89** [comment]
Ok, thanks for testing. I merged the scripts and updated the documentation.
